'use client';
import type { Metadata } from "next";
import { useEffect } from 'react';
import localFont from "next/font/local";
import { Provider } from 'react-redux';
import { PersistGate } from 'redux-persist/integration/react'; 
import { store, persistor } from '../store';
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Demo Website",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  useEffect(() => {
    // Ensure scrolling is enabled
    document.body.style.overflow = 'auto';
    return () => {
      // Reset on unmount
      document.body.style.overflow = 'auto';
    };
  }, []);

  return (
    
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <Provider store={store}>
              <PersistGate loading={<div>Loading...</div>} persistor={persistor}>
                {children}
              </PersistGate>
            </Provider>
          </body>
        </html>
      
  );
}
